version: "3.7"

services:
  rampvis-ontology-ui:
    container_name: rampvis-ontology-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/ui"
      - "/usr/src/ui/node_modules"
    ports:
      - "4200:4200"

networks:
  default:
    external: true
    name: rampvis-api-network
